services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6w8e43z5df6
      POSTGRES_DB: messager
    ports:
      - "5432:5432"
    networks:
      - app-network
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - app-network
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - postgres
      - adminer
    ports:
      - "3000:3000"
    working_dir: /app
    networks:
      - app-network
    command: [sh, -c, 'npm run start:dev']
    volumes:
      - .:/app:delegated
      - /app/node_modules

networks:
  app-network:
    driver: bridge
